name: Test BEST

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
            - os: ubuntu-20.04
              python-version: '3.6.12'
            - os: ubuntu-20.04
              python-version: '3.7'
            - os: ubuntu-20.04
              python-version: '3.8'
            - os: ubuntu-20.04
              python-version: '3.9'
            - os: ubuntu-20.04
              python-version: '3.10'

            - os: macos-latest
              python-version: '3.6.12'
            - os: macos-latest
              python-version: '3.7'
            - os: macos-latest
              python-version: '3.8'
            - os: macos-latest
              python-version: '3.9'
            - os: macos-latest
              python-version: '3.10'

            - os: windows-latest
              python-version: '3.7'
            - os: windows-latest
              python-version: '3.8'
            - os: windows-latest
              python-version: '3.9'
            - os: windows-latest
              python-version: '3.10'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install numpy
        pip install wheel
    - name: Setup package
      run:
        python setup.py bdist_wheel sdist

    - name: Install package
      run:
        pip install .

    - name: Test package
      run:
        python -m unittest


  release:
    if: contains(github.ref, 'refs/tags/')
    needs: test

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
            - os: ubuntu-20.04
              python-version: '3.6.12'
              docker_python_version: 'cp36-cp36m'
    steps:

    - uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    # Set up python after manylinux build otherwise it interferes with auditwheel in the image
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        pip install twine
        pip install wheel
    - name: Setup package
      run:
        python setup.py bdist_wheel sdist

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_Token_General }}
      run: |
        twine upload --skip-existing dist/*